language: java
sudo: true
jdk: oraclejdk8
before_install:
  - chmod +x mvnw
addons:
  sonarcloud:
    organization: "aghigo-github"
    token:
      secure: "b98e1088885c2bd91df964efe11ccb4aae26fb89" # encrypted value of your token
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent -Pcoverage install sonar:sonar
after_success:
  - mvn org.jacoco:jacoco-maven-plugin:report -Pcoverage org.eluder.coveralls:coveralls-maven-plugin:report -Pcoverage